"""add badge events table

Revision ID: 607534e0b107
Revises: 9765f201f683
Create Date: 2026-06-15 15:04:37.300089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607534e0b107'
down_revision = '9765f201f683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_badge_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badge_events'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('badge_events')
    # ### end Alembic commands ###
