"""add activity model

Revision ID: b79b103eeb1b
Revises: 35d654633ed5
Create Date: 2026-06-15 14:40:43.053460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79b103eeb1b'
down_revision = '35d654633ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_activities_name'), ['name'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_projects_code'), ['code'])

    with op.batch_alter_table('timesheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_timesheets_activity_id_activities'), 'activities', ['activity_id'], ['id'])
        batch_op.drop_column('activity_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_description', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_timesheets_activity_id_activities'), type_='foreignkey')
        batch_op.drop_column('activity_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_projects_code'), type_='unique')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_activities_name'), type_='unique')
    op.drop_table('activities')

    # ### end Alembic commands ###
