"""add smartworking and trasferta fields

Revision ID: fd7cda153c56
Revises: b79b103eeb1b
Create Date: 2026-06-15 14:46:34.978037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7cda153c56'
down_revision = 'b79b103eeb1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_smartworking', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_trasferta', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheets', schema=None) as batch_op:
        batch_op.drop_column('is_trasferta')
        batch_op.drop_column('is_smartworking')

    # ### end Alembic commands ###
